/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TournamentId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentType = IDL.Variant({
  'duo' : IDL.Null,
  'squad' : IDL.Null,
});
export const Time = IDL.Int;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'status' : PaymentStatus,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'tournamentId' : TournamentId,
});
export const PhoneNumber = IDL.Text;
export const FFUID = IDL.Nat;
export const TeamMember = IDL.Record({
  'age' : IDL.Nat,
  'email' : IDL.Text,
  'gameName' : IDL.Text,
  'phoneNumber' : PhoneNumber,
  'ffUID' : FFUID,
});
export const InstagramID = IDL.Text;
export const UPI = IDL.Text;
export const TeamInfo = IDL.Record({
  'members' : IDL.Vec(TeamMember),
  'teamLeaderInsta' : InstagramID,
  'teamLeaderUPI' : UPI,
});
export const TournamentRegistration = IDL.Record({
  'teamInfo' : TeamInfo,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'tournamentId' : TournamentId,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gameName' : IDL.Text,
  'phoneNumber' : PhoneNumber,
  'ffUID' : FFUID,
});
export const Tournament = IDL.Record({
  'id' : TournamentId,
  'tournamentType' : TournamentType,
  'entryFee' : IDL.Nat,
  'prize' : IDL.Nat,
  'timeSlot' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePayment' : IDL.Func([IDL.Principal, TournamentId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkDuplicateRegistration' : IDL.Func(
      [TournamentId],
      [IDL.Bool],
      ['query'],
    ),
  'createTournament' : IDL.Func(
      [TournamentId, TournamentType, Time, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getAllRegistrations' : IDL.Func(
      [],
      [IDL.Vec(TournamentRegistration)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentStatus' : IDL.Func([TournamentId], [PaymentStatus], ['query']),
  'getUserHistory' : IDL.Func([], [IDL.Vec(TournamentRegistration)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'registerTournament' : IDL.Func([TournamentId, TeamInfo], [IDL.Text], []),
  'rejectPayment' : IDL.Func([IDL.Principal, TournamentId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TournamentId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentType = IDL.Variant({ 'duo' : IDL.Null, 'squad' : IDL.Null });
  const Time = IDL.Int;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'status' : PaymentStatus,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'tournamentId' : TournamentId,
  });
  const PhoneNumber = IDL.Text;
  const FFUID = IDL.Nat;
  const TeamMember = IDL.Record({
    'age' : IDL.Nat,
    'email' : IDL.Text,
    'gameName' : IDL.Text,
    'phoneNumber' : PhoneNumber,
    'ffUID' : FFUID,
  });
  const InstagramID = IDL.Text;
  const UPI = IDL.Text;
  const TeamInfo = IDL.Record({
    'members' : IDL.Vec(TeamMember),
    'teamLeaderInsta' : InstagramID,
    'teamLeaderUPI' : UPI,
  });
  const TournamentRegistration = IDL.Record({
    'teamInfo' : TeamInfo,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'tournamentId' : TournamentId,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gameName' : IDL.Text,
    'phoneNumber' : PhoneNumber,
    'ffUID' : FFUID,
  });
  const Tournament = IDL.Record({
    'id' : TournamentId,
    'tournamentType' : TournamentType,
    'entryFee' : IDL.Nat,
    'prize' : IDL.Nat,
    'timeSlot' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePayment' : IDL.Func([IDL.Principal, TournamentId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkDuplicateRegistration' : IDL.Func(
        [TournamentId],
        [IDL.Bool],
        ['query'],
      ),
    'createTournament' : IDL.Func(
        [TournamentId, TournamentType, Time, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(TournamentRegistration)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentStatus' : IDL.Func([TournamentId], [PaymentStatus], ['query']),
    'getUserHistory' : IDL.Func(
        [],
        [IDL.Vec(TournamentRegistration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'registerTournament' : IDL.Func([TournamentId, TeamInfo], [IDL.Text], []),
    'rejectPayment' : IDL.Func([IDL.Principal, TournamentId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };