/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FFUID = bigint;
export type InstagramID = string;
export interface PaymentRequest {
  'status' : PaymentStatus,
  'userId' : Principal,
  'timestamp' : Time,
  'tournamentId' : TournamentId,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type PhoneNumber = string;
export interface TeamInfo {
  'members' : Array<TeamMember>,
  'teamLeaderInsta' : InstagramID,
  'teamLeaderUPI' : UPI,
}
export interface TeamMember {
  'age' : bigint,
  'email' : string,
  'gameName' : string,
  'phoneNumber' : PhoneNumber,
  'ffUID' : FFUID,
}
export type Time = bigint;
export interface Tournament {
  'id' : TournamentId,
  'tournamentType' : TournamentType,
  'entryFee' : bigint,
  'prize' : bigint,
  'timeSlot' : Time,
}
export type TournamentId = string;
export interface TournamentRegistration {
  'teamInfo' : TeamInfo,
  'userId' : Principal,
  'timestamp' : Time,
  'tournamentId' : TournamentId,
}
export type TournamentType = { 'duo' : null } |
  { 'squad' : null };
export type UPI = string;
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'email' : string,
  'gameName' : string,
  'phoneNumber' : PhoneNumber,
  'ffUID' : FFUID,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePayment' : ActorMethod<[Principal, TournamentId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkDuplicateRegistration' : ActorMethod<[TournamentId], boolean>,
  'createTournament' : ActorMethod<
    [TournamentId, TournamentType, Time, bigint, bigint],
    undefined
  >,
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getAllRegistrations' : ActorMethod<[], Array<TournamentRegistration>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaymentStatus' : ActorMethod<[TournamentId], PaymentStatus>,
  'getUserHistory' : ActorMethod<[], Array<TournamentRegistration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTournaments' : ActorMethod<[], Array<Tournament>>,
  'registerTournament' : ActorMethod<[TournamentId, TeamInfo], string>,
  'rejectPayment' : ActorMethod<[Principal, TournamentId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];